const languageCodes: { [key: string]: string } = {
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  pt: "Portuguese",
  ru: "Russian",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  ar: "Arabic",
  hi: "Hindi",
  bn: "Bengali",
  ms: "Malay",
  ta: "Tamil",
  te: "Telugu",
  vi: "Vietnamese",
  th: "Thai",
  tr: "Turkish",
  pl: "Polish",
  cs: "Czech",
  el: "Greek",
  sv: "Swedish",
  nl: "Dutch",
  hu: "Hungarian",
  ro: "Romanian",
  sr: "Serbian",
  hr: "Croatian",
  sk: "Slovak",
  sl: "Slovenian",
  da: "Danish",
  fi: "Finnish",
  no: "Norwegian",
  et: "Estonian",
  lv: "Latvian",
  lt: "Lithuanian",
  is: "Icelandic",
  ga: "Irish",
  gd: "Scottish Gaelic",
  cy: "Welsh",
};

export default languageCodes;
